- name: Create EC2 instance
  hosts: local
  gather_facts: False
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: ansible-kp
        instance_type: t2.micro
        image_id: ami-08718895af4dfa033
        region: ap-south-1
        wait: yes
        count: 1
        tags:
          Name: Ansible_EC2
      register: ec2
